<#
.SYNOPSIS
    Part of the PSTaskFramework.
.NOTES
    SPDX-License-Identifier: Unlicense
    Source: http://github.com/mrfootoyou/pstaskframework
#>
#Requires -Version 7.4

using module .\PSTaskFramework.classes.psm1
param()

function Get-TaskFrameworkHelp {
    <#
    .DESCRIPTION
        Generates help for a task defined in the task framework. If a task name is not
        specified, it generates help for the build script itself.

        The help output is generated by merging the help info from the build script and the
        task action. This allows the task help to include information about the build script's
        parameters and syntax, which is relevant when invoking the task via the build script.
    .OUTPUTS
        [System.String]
        The formatted help string.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        # The name of the task to show help for. If not specified, shows help for the build script itself.
        [string]$TaskName,

        # The arguments to pass to Get-Help when retrieving help info for the build script and task action.
        [ValidateNotNull()]
        [hashtable]$GetHelpArgs = @{},

        # The task context hashtable. Defaults to the current task context returned by Get-TaskFrameworkContext.
        [ValidateNotNull()]
        [TaskContext]$TaskContext = (Get-TaskFrameworkContext)
    )
    Sync-CallerPreference

    $helpTaskName = $TaskContext.HelpTaskName ?? $TaskContext.CurrentTask.Name ?? 'help'
    $buildScriptPath = $TaskContext.BuildScriptPath
    $taskNameArgName = $TaskContext.TaskNameArgName ?? 'TaskName'
    $taskArgsArgName = $TaskContext.TaskArgsArgName ?? 'TaskArgs'

    # Get the help info for the build script. We will merge it's parameters and syntax
    # with the task help info to produce the final help output.
    if (!$buildScriptPath) {
        throw 'The build script path is not available. Specify it when calling Initialize-TaskFramework.'
    }
    $buildHelp = Get-Help -Name $buildScriptPath @GetHelpArgs
    if (!$buildHelp) { return }

    if (-not ($buildHelp.parameters.parameter.name -eq $taskNameArgName)) {
        Write-Warning "Parameter '$taskNameArgName' was not found in the build script. Specify the actual parameter name in Initialize-TaskFramework."
    }
    if (-not ($buildHelp.parameters.parameter.name -eq $taskArgsArgName)) {
        Write-Warning "Parameter '$taskArgsArgName' was not found in the build script. Specify the actual parameter name in Initialize-TaskFramework."
    }

    function normalizeText([string]$text) {
        # trim and normalize line endings to CR to simplify regexes
        $text = $text -creplace '\s*?\r?\n', "`n"
        return $text
    }
    function finalizeText([string]$text) {
        # Assumes CR line endings.
        # remove empty section
        $text = $text -creplace '(?m)^(SYNOPSIS|DESCRIPTION|INPUTS|OUTPUTS|RELATED LINKS)\n\n+', ''
        # collapse consecutive empty lines
        $text = $text -creplace '\n\n\n+', "`n`n"
        # trim trailing empty lines to at most 1
        $text = $text -creplace '\n\n$', "`n"
        # convert to the environment's newline
        $text = $text -creplace '\r?\n', [Environment]::NewLine
        return $text
    }

    # If no task name specified, show the build script help
    if (!$TaskName) {
        $text = normalizeText ($buildHelp | Out-String)
        return finalizeText $text
    }

    # Get the specified task...
    $task = getTask $TaskName -TaskContext $TaskContext -ea Ignore
    if (-not $task) {
        throw "Task '$TaskName' not found."
    }

    $TaskName = $task.Name # use the canonical name
    $taskDescription = $task.Description
    if ($taskDescription) {
        # ensure ends with a period
        $taskDescription = $taskDescription -replace '\.\s*$', '.'
    }
    $taskAction = $task.Action ?? ([scriptblock]::Create("
        <#
        .DESCRIPTION
            This is a `"meta-task`" that only serves as a grouping of dependencies.
            No additional help is available for this task.
        #>
        param()"))

    # Use the taskAction to generate a temporary function that we can call Get-Help on to generate the
    # help info. We use a unique name to aid in regex replacements later.
    $functionName = "_$([Guid]::NewGuid().ToString('N'))"
    $tempModule = New-Module -ScriptBlock ([scriptblock]::Create("function $functionName {$taskAction.Ast.ParamBlock}"))
    $taskHelp = Get-Help $functionName @GetHelpArgs
    $tempModule | Remove-Module

    # Fixup the help object...
    function mamlParaTextItem($text) {
        return [PSObject]@{ Text = $text; type = 'text' } |
        Add-Member -TypeName 'MamlParaTextItem' -PassThru
    }
    function mamlParaText([string[]]$text) {
        # must return an array of ParaTextItem
        return , $text.ForEach{ mamlParaTextItem $_ }
    }

    # remove the ModuleName member
    if ($taskHelp.ModuleName) {
        $null = $taskHelp.PSObject.Members.Remove('ModuleName')
    }

    # fix the name
    $taskHelp.details | Add-Member 'name' $TaskName -Force
    $taskHelp | Add-Member 'Name' $TaskName -Force

    # set Synopsis using the task description, if missing
    if ($taskDescription) {
        if (!$taskHelp.details.description) {
            $taskHelp.details | Add-Member 'description' (mamlParaText $taskDescription) -Force
        }
        if (!$taskHelp.Synopsis) {
            $taskHelp | Add-Member 'Synopsis' $taskDescription -Force
        }
    }

    # merge the build script's parameters and syntax into the task's help...
    $taskCommonParameters = $task.Action -and ($taskHelp.CommonParameters ?? $true)
    $buildCommonParameters = $task.Action -and ($buildHelp.CommonParameters ?? $true)

    $dashSwitch = [PSObject]@{
        name          = '-'
        description   = mamlParaText 'A meta-parameter used to separate build script parameters from task parameters.'
        required      = $false
        globbing      = $false
        pipelineInput = $false
        position      = 'named'
    } | Add-Member -TypeName 'MamlCommandHelpInfo#parameter' -PassThru

    # Update the description of the 'TaskName' parameter to indicate the value it should have to invoke the task.
    foreach ($param in $buildHelp.parameters.parameter) {
        if ($param.name -eq $taskNameArgName) {
            $param.description = mamlParaText "The name of the task to execute. '$TaskName' in this case."
            break
        }
    }

    # Merge parameters:
    # We omit the build script's 'TaskArgs' parameters since the actual task args are already included.
    if ($null -eq $taskHelp.parameters) {
        $taskHelp | Add-Member 'parameters' ([PSCustomObject]@{ parameter = @() } | Add-Member -TypeName 'ExtendedCmdletHelpInfo#parameters' -PassThru) -Force
    }
    if ($null -eq $taskHelp.parameters.parameter) {
        $taskHelp.parameters | Add-Member 'parameter' @() -Force
    }
    $taskHelp.parameters.parameter = @(
        $buildHelp.parameters.parameter.where{ $_.name -ne $taskArgsArgName }
        if ($taskHelp.parameters.parameter.Count -or $taskCommonParameters) { $dashSwitch }
        $taskHelp.parameters.parameter
    )

    # Merge Syntax:
    # We omit the 'TaskName' parameter itself since the task name is fixed in this context.
    # We only include those build script syntax items that include the 'TaskName' parameter
    # since those are the ones relevant to invoking tasks.
    $buildSyntaxItems = $buildHelp.syntax.syntaxItem.where{ $_.parameter.name -eq $TaskNameArgName }

    if ($null -eq $taskHelp.syntax) {
        $taskHelp | Add-Member 'syntax' ([PSCustomObject]@{ syntaxItem = @() }) -Force
    }
    if ($null -eq $taskHelp.syntax.syntaxItem) {
        $taskHelp.syntax | Add-Member 'syntaxItem' @() -Force
    }
    if ($taskHelp.syntax.syntaxItem.Count -eq 0) {
        # add a default syntaxItem so that we have somewhere to merge the build script syntax into
        $taskHelp.syntax.syntaxItem += [PSCustomObject]@{
            name      = $functionName
            parameter = @()
        } | Add-Member -TypeName 'MamlCommandHelpInfo#syntaxItem' -PassThru
    }
    $taskHelp.syntax.syntaxItem = @(
        foreach ($buildSyntaxItem in $buildSyntaxItems) {
            $buildParams = $buildSyntaxItem.parameter.where{ $_.name -notin $taskNameArgName, $taskArgsArgName }
            foreach ($item in $taskHelp.syntax.syntaxItem) {
                $copy = $item.PSObject.Copy() # shallow copy
                $copy.name = "$buildScriptPath [-$taskNameArgName] $TaskName"
                $copy | Add-Member 'parameter' @(
                    $buildParams
                    if ($item.parameter.Count -or $taskCommonParameters) { $dashSwitch }
                    $item.parameter
                ) -Force
                $copy
            }
        }
    )

    # The remaining fixups are done via text manipulation on the help output.
    $text = normalizeText ($taskHelp | Out-String)
    function escapeRegex([string]$s) { return [regex]::Escape($s) }
    function escapeReplacement([string]$s) { return $s.Replace('$', '$$') }

    # change NAME heading to TASK NAME
    $text = $text -creplace '(?m)^NAME$', 'TASK NAME'
    # replace the temp function name with the build script help invocation.
    $text = $text -creplace $functionName, (escapeReplacement "$buildScriptPath $TaskName")

    # Insert 'DEPENDS ON' section before RELATED LINKS or REMARKS
    if ($text -match '(?m)^(RELATED LINKS|REMARKS)$') {
        $insertBefore = $Matches[1]
        $dependsOnText = @(
            if ($task.DependsOn) {
                'This task depends on the following tasks:'
                $task.DependsOn.foreach{ "- $_" }
            }
            else {
                'This task has no task dependencies.'
            }
        )
        $dependsOnText = "DEPENDS ON`n    $($dependsOnText -join "`n    ")"
        $text = $text -creplace "(?m)^$insertBefore`$", "$(escapeReplacement $dependsOnText)`n`n`$0"
    }

    if ($buildCommonParameters) {
        # Insert build script's "[<CommonParameters>]" before the '--' separator
        $text = $text -creplace "($(escapeRegex $buildScriptPath) .*?)(\[--])", '$1[<CommonParameters>] $2'
    }
    if ($taskCommonParameters) {
        # Rename the task's [<CommonParameters>] (the one after the '--') to avoid confusion with the
        # build script's common parameters
        $text = $text -creplace "($(escapeRegex $buildScriptPath) .*? \[--] .*?)\[\<CommonParameters\>\]", '$1[<TaskCommonParameters>]'
    }

    # fixup the additional help remarks
    $text = $text -creplace "Get-Help $(escapeRegex $TaskName) ", "$(escapeReplacement "$buildScriptPath $HelpTaskName $TaskName") -- "

    return finalizeText $text
}
