#
# Module manifest for module 'PSTaskFramework'
#
# Generated by: John Belcher
#
# Generated on: 4/13/2026
#

@{

    # Version number of this module.
    ModuleVersion        = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('core')

    # ID used to uniquely identify this module
    GUID                 = 'edf95624-06d1-4139-afc9-740afebc8e06'

    # Author of this module
    Author               = 'John Belcher'

    # Company or vendor of this module
    CompanyName          = 'John Belcher'

    # Copyright statement for this module
    Copyright            = '(c) 2026 John Belcher'

    # Description of the functionality provided by this module
    Description          = 'A lightweight PowerShell task framework for defining and invoking tasks with dependencies.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.4'

    # Script module or binary module file associated with this manifest.
    RootModule           = 'PSTaskFramework.psm1'

    # Modules to import as nested modules of the module specified in RootModule
    # NestedModules        = @()

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules      = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Reset-TaskFramework'
        'Task'
        'Get-TaskFrameworkTasks'
        'Invoke-TaskFramework'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('task', 'build', 'framework', 'automation', 'powershell', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')

            # A URL to the license for this module.
            LicenseUri   = 'https://unlicense.org/'

            # A URL to the main website for this project.
            ProjectUri   = 'http://github.com/mrfootoyou/pstaskframework'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/mrfootoyou/pstaskframework/releases/tag/1.0.0'

            # Prerelease string of this module
            Prerelease   = ''
        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

