# spell:ignore quotepath mmdc stefanzweifel
name: "Generate Diagrams"

on:
  push:
    branches-ignore:
      - main # protected
  workflow_dispatch:
    inputs:
      diagrams:
        description: |
          Comma-separated list of diagram files to process (supports glob patterns)
        required: true
        default: "**/*.mmd"

env:
  MERMAID_CLI_VERSION: "11.12.0"
  MERMAID_CONFIG_PATH: ./docs/generated/mermaid-config.json
  PUPPETEER_CONFIG_PATH: ./docs/generated/puppeteer-config.json
  IMAGE_OUTPUT_DIR: ./docs/generated
  IMAGE_TYPE: png,svg

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-diagrams:
    name: Generate diagrams
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Default values. Will be overridden below.
      ANY_CHANGED: false
      CHANGED_FILES_JSON: ""
      ANY_DELETED: false
      DELETED_FILES_JSON: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get changed files (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        shell: pwsh
        env:
          INPUT_DIAGRAMS: ${{ github.event.inputs.diagrams }}
        run: |
          # For manual triggers, we need to resolve the input glob patterns to actual
          # file paths. We ignore any paths that are outside the repository.
          $changedFiles = (
              "$env:INPUT_DIAGRAMS".Split(',') |
              ForEach-Object { $_.Trim() -replace '^\*\*/','' } |
              ForEach-Object { if ($_) { git ls-files "$_" } } |
              Select-Object -Unique
          )
          echo "ANY_CHANGED=$($changedFiles.Count -gt 0)" >> $GITHUB_ENV
          echo "CHANGED_FILES_JSON=$($changedFiles | ConvertTo-Json -Compress -AsArray)" >> $GITHUB_ENV

      - name: Get changed files (event trigger)
        id: changed_files
        if: github.event_name != 'workflow_dispatch'
        uses: tj-actions/changed-files@v47
        with:
          output_renamed_files_as_deleted_and_added: true
          json: true
          escape_json: false
          files: |
            **/*.mmd

      - name: Set environment variables
        if: steps.changed_files.outcome == 'success'
        env:
          ANY_CHANGED: ${{ steps.changed_files.outputs.any_changed == 'true' }}
          CHANGED_FILES_JSON: ${{ steps.changed_files.outputs.all_changed_files }}
          ANY_DELETED: ${{ steps.changed_files.outputs.any_deleted == 'true' }}
          DELETED_FILES_JSON: ${{ steps.changed_files.outputs.deleted_files }}
        run: |
          echo "ANY_CHANGED=$ANY_CHANGED" >> $GITHUB_ENV
          echo "CHANGED_FILES_JSON=$CHANGED_FILES_JSON" >> $GITHUB_ENV
          echo "ANY_DELETED=$ANY_DELETED" >> $GITHUB_ENV
          echo "DELETED_FILES_JSON=$DELETED_FILES_JSON" >> $GITHUB_ENV

      - name: Setup Node.js
        if: env.ANY_CHANGED == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install mermaid-cli
        if: env.ANY_CHANGED == 'true'
        run: npm install -g "@mermaid-js/mermaid-cli@$MERMAID_CLI_VERSION"

      - name: Install Google Fonts (Recursive)
        if: env.ANY_CHANGED == 'true'
        uses: jim60105/action-install-google-fonts@v2
        with:
          fonts: Recursive

      - name: Generate diagram images
        if: env.ANY_CHANGED == 'true'
        shell: pwsh
        run: |
          "$env:CHANGED_FILES_JSON" | ConvertFrom-Json | ForEach-Object -Parallel {
              $file = Get-Item $_
              foreach ($ext in $env:IMAGE_TYPE.Split(',')) {
                  $imagePath = Join-Path $env:IMAGE_OUTPUT_DIR ([System.IO.Path]::ChangeExtension($file.Name, $ext))
                  Write-Host "Processing: '$file' -> '$imagePath'"

                  mmdc `
                      --input $file `
                      --output $imagePath `
                      --scale 4 `
                      --svgId diegl `
                      --configFile $env:MERMAID_CONFIG_PATH `
                      --puppeteerConfigFile $env:PUPPETEER_CONFIG_PATH
              }
          }

      - name: Delete orphaned diagram images
        if: env.ANY_DELETED == 'true'
        shell: pwsh
        run: |
          "$env:DELETED_FILES_JSON" | ConvertFrom-Json | ForEach-Object {
              $fileName = Split-Path $_ -Leaf
              foreach ($ext in $env:IMAGE_TYPE.Split(',')) {
                  $imagePath = Join-Path $env:IMAGE_OUTPUT_DIR ([System.IO.Path]::ChangeExtension($fileName, $ext))
                  if (Test-Path $imagePath) {
                      Write-Host "Deleting orphaned diagram image: '$imagePath'"
                      Remove-Item $imagePath
                  }
              }
          }

      - name: Atomic commit
        id: auto_commit_action
        if: env.ANY_CHANGED == 'true' || env.ANY_DELETED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: "${{ env.IMAGE_OUTPUT_DIR }}/*"
          commit_message: "docs(diagrams): automatically generated diagram images"

      - name: "${{ steps.auto_commit_action.outputs.changes_detected == 'true' &&
          'Changes pushed ⚡' || 'No changes ✅' }}"
        if: steps.auto_commit_action.outputs.changes_detected == 'true'
        run: |
          echo "Commit ID: ${{ steps.auto_commit_action.outputs.commit_hash }}"
